name: C CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y build-essential && curl -o test/unity.c https://raw.githubusercontent.com/ThrowTheSwitch/Unity/master/src/unity.c && curl -o test/unity.h https://raw.githubusercontent.com/ThrowTheSwitch/Unity/master/src/unity.h 
        
    - name: Build and run tests
      run: make test
